<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <LangVersion>12</LangVersion>
    <RootNamespace>RecoilNet</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\.editorconfig" Link=".editorconfig" />
    <PackageReference Include="Nullable" Version="1.3.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Threading.Channels" Version="9.0.8" />
    <PackageReference Include="Vogen" Version="8.0.1" />
    <None Update="AtomFamily.tt">
      <LastGenOutput>AtomFamily.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="Atom.tt">
      <LastGenOutput>Atom.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="Templates\Recoil.ttinclude">
      <Generator></Generator>
    </None>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
    <Compile Update="AtomFamily.cs">
      <DependentUpon>AtomFamily.tt</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Atom.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Atom.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
