<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Page Remove="RecoilRoot.xaml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="RecoilRoot.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Recoil.net\Recoil.net.csproj" />
  </ItemGroup>

</Project>
